language: python
matrix:
  include:
    - name: "Python 3.7.2 on Xenial Linux"
      python: 3.7.2
      dist: xenial
    - name: "Python 2.7.15 on Xenial Linux"
      python: 2.7.15
      dist: xenial
install: pip install -e .
script: py.test --disable-pytest-warnings
