language: python
matrix:
  include:
    - name: "Python 3.7.2 on Xenial Linux"
      python: 3.7.2
      dist: xenial
    - name: "Python 2.7.15 on Xenial Linux"
      python: 2.7.15
      dist: xenial
install: python setup.py develop
script: py.test --disable-pytest-warnings