FROM ubuntu

RUN  apt-get update && apt-get install -y  python3-all \
    python3-venv \
    python3-dev \
    python3-setuptools \
    libpq-dev \
    build-essential \
    binutils \
    g++

COPY . /var/pyzz/
WORKDIR /var/pyzz/
RUN python3 -m venv /var/venv/
RUN /var/venv/bin/pip install --upgrade pip
RUN /var/venv/bin/pip install .
